version: 0.2
env:
  variables:
    S3_ENVIRONMENT_BUCKET: s3://envfolder/testing/test/.env
phases:
  pre_build:
    commands:
      - echo
      - - echo "S3 bucket is S3_ENVIRONMENT_BUCKET"
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 829586007552.dkr.ecr.eu-west-2.amazonaws.com
      - REPOSITORY_URI=829586007552.dkr.ecr.eu-west-2.amazonaws.com/demoplay
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"httpd","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json